1.	Create a matrix calculator in phyton that performs that should be able to do the following

a.	Add two matrices

b.	Subtract two matrices

c.	Multiply two matrices

d.	Find the transpose of a matrix

e.	Find the inverse of a matrix

f.	Other things that make your program amazing!!


In [ ]:
#Add two matrices:
import numpy as np
dimension1 = str(input("Please choose dimension for matrix A: "))
dimension2 = str(input("Please choose dimension for matrix B: "))
if dimension1 == "3x3" and dimension2 =="3x3" and dimension1 == dimension2:
    note = "Matrix A is 3x3 and Matrix B is 3x3"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    d=float(input("Matrix A, 4th position: "))
    e=float(input("Matrix A, 5th position: "))
    f=float(input("Matrix A, 6th position: "))
    g=float(input("Matrix A, 7th position: "))
    h=float(input("Matrix A, 8th position: "))
    i=float(input("Matrix A, 9th position: "))
    threexthree1 = np.array([[ a, b, c],[ d, e, f],[g ,h ,i]])
    print(threexthree1)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    c1=float(input("Matrix B, 3rd position: "))
    d1=float(input("Matrix B, 4th position: "))
    e1=float(input("Matrix B, 5th position: "))
    f1=float(input("Matrix B, 6th position: "))
    g1=float(input("Matrix B, 7th position: "))
    h1=float(input("Matrix B, 8th position: "))
    i1=float(input("Matrix B, 9th position: "))
    threexthree2 = np.array([[ a1, b1, c1],[ d1, e1, f1],[g1 ,h1 ,i1]])
    print(threexthree2)
    threexthree = np.array([[ a+a1, b+b1, c+c1],[ d+d1, e+e1, f+f1],[g+g1 ,h+h1 ,i+i1]])
    print("Result of Matrix A + Matrix B:")
    print(threexthree)
elif dimension1 == "3x2" and dimension2 == "3x2" and dimension1 == dimension2:
    note = "Matrix A is 3x2 and Matrix B is 3x2"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    d=float(input("Matrix A, 4th position: "))
    e=float(input("Matrix A, 5th position: "))
    f=float(input("Matrix A, 6th position: "))
    threexthree1 = np.array([[ a, b, c],[ d, e, f]])
    print(threexthree1)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    c1=float(input("Matrix B, 3rd position: "))
    d1=float(input("Matrix B, 4th position: "))
    e1=float(input("Matrix B, 5th position: "))
    f1=float(input("Matrix B, 6th position: "))
    threexthree2 = np.array([[ a1, b1, c1],[ d1, e1, f1]])
    print(threexthree2)
    print("Result of Matrix A + Matrix B:")
    threexthree = np.array([[ a+a1, b+b1, c+c1],[ d+d1, e+e1, f+f1]])
    print(threexthree)
elif dimension1 == "3x1" and dimension2 == "3x1" and dimension1 == dimension2:
    note = "Matrix A is 3x1 and Matrix B is 3x1"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    threexthree1 = np.array([[ a, b, c]])
    print(threexthree1)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    c1=float(input("Matrix B, 3rd position: "))
    threexthree2 = np.array([[ a1, b1, c1]])
    print(threexthree2)
    print("Result of Matrix A + Matrix B:")
    threexthree = np.array([[ a+a1, b+b1, c+c1]])
    print(threexthree)
elif dimension1 == "2x3" and dimension2 == "2x3" and dimension1 == dimension2:
    note = "Matrix A is 2x3 and Matrix B is 2x3"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    d=float(input("Matrix A, 4th position: "))
    e=float(input("Matrix A, 5th position: "))
    f=float(input("Matrix A, 6th position: "))  
    threexthree1 = np.array([[ a, b],[ c, d],[ e, f]])
    print(threexthree1)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    c1=float(input("Matrix B, 3rd position: "))
    d1=float(input("Matrix B, 4th position: "))
    e1=float(input("Matrix B, 5th position: "))
    f1=float(input("Matrix B, 6th position: "))
    threexthree2 = np.array([[ a1, b1],[ c1, d1],[ e1, f1]])
    print(threexthree2)
    print("Result of Matrix A + Matrix B:")
    threexthree = np.array([[a+a1, b+b1],[c+c1, d+d1],[e+e1, f+f1]])
    print(threexthree)
elif dimension1 == "2x2" and dimension2 == "2x2" and dimension1 == dimension2:
    note = "Matrix A is 2x2 and Matrix B is 2x3"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    d=float(input("Matrix A, 4th position: "))
    threexthree1 = np.array([[ a, b],[ c, d]])
    print(threexthree1)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    c1=float(input("Matrix B, 3rd position: "))
    d1=float(input("Matrix B, 4th position: "))
    threexthree2 = np.array([[ a1, b1],[ c1, d1]])
    print(threexthree2)
    print("Result of Matrix A + Matrix B:")
    threexthree = np.array([[a+a1, b+b1],[c+c1, d+d1]])
    print(threexthree)
elif dimension1 == "2x1" and dimension2 == "2x1" and dimension1 == dimension2:
    note = "Matrix A is 2x1 and Matrix B is 2x1"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    threexthree1 = np.array([[ a, b]])
    print(threexthree1)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    threexthree2 = np.array([[ a1, b1]])
    print(threexthree2)
    print("Result of Matrix A + Matrix B:")
    threexthree = np.array([[a+a1, b+b1]])
    print(threexthree)
elif dimension1 == "1x3" and dimension2 == "1x3" and dimension1 == dimension2:
    note = "Matrix A is 1x3 and Matrix B is 1x3"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    threexthree1 = np.array([[ a, b, c]])
    print(threexthree1)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    c1=float(input("Matrix B, 3rd position: "))
    threexthree2 = np.array([[ a1, b1, c1]])
    print(threexthree2)
    print("Result of Matrix A + Matrix B:")
    threexthree = np.array([[a+a1, b+b1, c+c1]])
    print(threexthree)
elif dimension1 == "1x2" and dimension2 == "1x2" and dimension1 == dimension2:
    note = "Matrix A is 1x2 and Matrix B is 1x2"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    threexthree1 = np.array([[ a, b]])
    print(threexthree1)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    threexthree2 = np.array([[ a1, b1]])
    print(threexthree2)
    print("Result of Matrix A + Matrix B:")
    threexthree = np.array([[a+a1, b+b1]])
    print(threexthree)
elif dimension1 == "1x1" and dimension2 == "1x1" and dimension1 == dimension2:
    note = "Matrix A is 1x1 and Matrix B is 1x1"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    threexthree1 = np.array([a])
    print(threexthree1)
    a1=float(input("Matrix B, 1st position: "))
    threexthree2 = np.array([a1])
    print(threexthree2)
    print("Result of Matrix A + Matrix B:")
    threexthree = np.array([a+a1])
    print(threexthree)

In [ ]:
#Substract two matrices
import numpy as np
dimension1 = str(input("Please choose dimension for matrix A: "))
dimension2 = str(input("Please choose dimension for matrix B: "))
if dimension1 == "3x3" and dimension2 =="3x3" and dimension1 == dimension2:
    note = "Matrix A is 3x3 and Matrix B is 3x3"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    d=float(input("Matrix A, 4th position: "))
    e=float(input("Matrix A, 5th position: "))
    f=float(input("Matrix A, 6th position: "))
    g=float(input("Matrix A, 7th position: "))
    h=float(input("Matrix A, 8th position: "))
    i=float(input("Matrix A, 9th position: "))
    threexthree1 = np.array([[ a, b, c],[ d, e, f],[g ,h ,i]])
    print(threexthree1)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    c1=float(input("Matrix B, 3rd position: "))
    d1=float(input("Matrix B, 4th position: "))
    e1=float(input("Matrix B, 5th position: "))
    f1=float(input("Matrix B, 6th position: "))
    g1=float(input("Matrix B, 7th position: "))
    h1=float(input("Matrix B, 8th position: "))
    i1=float(input("Matrix B, 9th position: "))
    threexthree2 = np.array([[ a1, b1, c1],[ d1, e1, f1],[g1 ,h1 ,i1]])
    print(threexthree2)
    threexthree = np.array([[ a-a1, b-b1, c-c1],[ d-d1, e-e1, f-f1],[g-g1 ,h-h1 ,i-i1]])
    print("Result of Matrix A - Matrix B:")
    print(threexthree)
elif dimension1 == "3x2" and dimension2 == "3x2" and dimension1 == dimension2:
    note = "Matrix A is 3x2 and Matrix B is 3x2"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    d=float(input("Matrix A, 4th position: "))
    e=float(input("Matrix A, 5th position: "))
    f=float(input("Matrix A, 6th position: "))
    threexthree1 = np.array([[ a, b, c],[ d, e, f]])
    print(threexthree1)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    c1=float(input("Matrix B, 3rd position: "))
    d1=float(input("Matrix B, 4th position: "))
    e1=float(input("Matrix B, 5th position: "))
    f1=float(input("Matrix B, 6th position: "))
    threexthree2 = np.array([[ a1, b1, c1],[ d1, e1, f1]])
    print(threexthree2)
    print("Result of Matrix A - Matrix B:")
    threexthree = np.array([[ a-a1, b-b1, c-c1],[ d-d1, e-e1, f-f1]])
    print(threexthree)
elif dimension1 == "3x1" and dimension2 == "3x1" and dimension1 == dimension2:
    note = "Matrix A is 3x1 and Matrix B is 3x1"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    threexthree1 = np.array([[ a, b, c]])
    print(threexthree1)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    c1=float(input("Matrix B, 3rd position: "))
    threexthree2 = np.array([[ a1, b1, c1]])
    print(threexthree2)
    print("Result of Matrix A - Matrix B:")
    threexthree = np.array([[ a-a1, b-b1, c-c1]])
    print(threexthree)
elif dimension1 == "2x3" and dimension2 == "2x3" and dimension1 == dimension2:
    note = "Matrix A is 2x3 and Matrix B is 2x3"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    d=float(input("Matrix A, 4th position: "))
    e=float(input("Matrix A, 5th position: "))
    f=float(input("Matrix A, 6th position: "))  
    threexthree1 = np.array([[ a, b],[ c, d],[ e, f]])
    print(threexthree1)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    c1=float(input("Matrix B, 3rd position: "))
    d1=float(input("Matrix B, 4th position: "))
    e1=float(input("Matrix B, 5th position: "))
    f1=float(input("Matrix B, 6th position: "))
    threexthree2 = np.array([[ a1, b1],[ c1, d1],[ e1, f1]])
    print(threexthree2)
    print("Result of Matrix A - Matrix B:")
    threexthree = np.array([[a-a1, b-b1],[c-c1, d-d1],[e-e1, f-f1]])
    print(threexthree)
elif dimension1 == "2x2" and dimension2 == "2x2" and dimension1 == dimension2:
    note = "Matrix A is 2x2 and Matrix B is 2x3"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    d=float(input("Matrix A, 4th position: "))
    threexthree1 = np.array([[ a, b],[ c, d]])
    print(threexthree1)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    c1=float(input("Matrix B, 3rd position: "))
    d1=float(input("Matrix B, 4th position: "))
    threexthree2 = np.array([[ a1, b1],[ c1, d1]])
    print(threexthree2)
    print("Result of Matrix A - Matrix B:")
    threexthree = np.array([[a-a1, b-b1],[c-c1, d-d1]])
    print(threexthree)
elif dimension1 == "2x1" and dimension2 == "2x1" and dimension1 == dimension2:
    note = "Matrix A is 2x1 and Matrix B is 2x1"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    threexthree1 = np.array([[ a, b]])
    print(threexthree1)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    threexthree2 = np.array([[ a1, b1]])
    print(threexthree2)
    print("Result of Matrix A - Matrix B:")
    threexthree = np.array([[a-a1, b-b1]])
    print(threexthree)
elif dimension1 == "1x3" and dimension2 == "1x3" and dimension1 == dimension2:
    note = "Matrix A is 1x3 and Matrix B is 1x3"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    threexthree1 = np.array([[ a, b, c]])
    print(threexthree1)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    c1=float(input("Matrix B, 3rd position: "))
    threexthree2 = np.array([[ a1, b1, c1]])
    print(threexthree2)
    print("Result of Matrix A - Matrix B:")
    threexthree = np.array([[a-a1, b-b1, c-c1]])
    print(threexthree)
elif dimension1 == "1x2" and dimension2 == "1x2" and dimension1 == dimension2:
    note = "Matrix A is 1x2 and Matrix B is 1x2"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    threexthree1 = np.array([[ a, b]])
    print(threexthree1)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    threexthree2 = np.array([[ a1, b1]])
    print(threexthree2)
    print("Result of Matrix A - Matrix B:")
    threexthree = np.array([[a-a1, b-b1]])
    print(threexthree)
elif dimension1 == "1x1" and dimension2 == "1x1" and dimension1 == dimension2:
    note = "Matrix A is 1x1 and Matrix B is 1x1"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    threexthree1 = np.array([a])
    print(threexthree1)
    a1=float(input("Matrix B, 1st position: "))
    threexthree2 = np.array([a1])
    print(threexthree2)
    print("Result of Matrix A - Matrix B:")
    threexthree = np.array([a-a1])
    print(threexthree)

In [66]:
#Multiply two matrices:
import numpy as np
dimension1 = str(input("Please choose dimension for matrix A: "))
dimension2 = str(input("Please choose dimension for matrix B: "))
if dimension1 == "3x3" and dimension2 == "3x3":
    note = "Matrix A is 3x3 and Matrix B is 3x3"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    d=float(input("Matrix A, 4th position: "))
    e=float(input("Matrix A, 5th position: "))
    f=float(input("Matrix A, 6th position: "))
    g=float(input("Matrix A, 7th position: "))
    h=float(input("Matrix A, 8th position: "))
    i=float(input("Matrix A, 9th position: "))
    matrixA = np.array([[ a, b, c],[ d, e, f],[g ,h ,i]])
    print(matrixA)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    c1=float(input("Matrix B, 3rd position: "))
    d1=float(input("Matrix B, 4th position: "))
    e1=float(input("Matrix B, 5th position: "))
    f1=float(input("Matrix B, 6th position: "))
    g1=float(input("Matrix B, 7th position: "))
    h1=float(input("Matrix B, 8th position: "))
    i1=float(input("Matrix B, 9th position: "))
    matrixB = np.array([[ a1, b1, c1],[ d1, e1, f1],[g1 ,h1 ,i1]])
    print(matrixB)
    print("Result of Matrix A multiply by Matrix B is: ")
    matrix = np.array([[a*a1+b*d1+c*g1, a*b1+b*e1+c*h1, a*c1+b*f1+c*i1],[d*a1+e*d1+f*g1, d*b1+e*f1+f*h1, d*c1+e*f1+f*i1],[g*a1+h*d1+i*g1, g*b1+h*e1+i*h1, g*c1+h*f1+i*i1]])
    print(matrix)
elif dimension1 == "3x3" and dimension2 == "2x3":
     print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "3x3" and dimension2 == "3x1":
     print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "3x3" and dimension2 == "3x2":
    note = "Matrix A is 3x3 and Matrix B is 3x2"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    d=float(input("Matrix A, 4th position: "))
    e=float(input("Matrix A, 5th position: "))
    f=float(input("Matrix A, 6th position: "))
    g=float(input("Matrix A, 7th position: "))
    h=float(input("Matrix A, 8th position: "))
    i=float(input("Matrix A, 9th position: "))
    matrixA = np.array([[ a, b, c],[ d, e, f],[g ,h ,i]])
    print(matrixA)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    c1=float(input("Matrix B, 3rd position: "))
    d1=float(input("Matrix B, 4th position: "))
    e1=float(input("Matrix B, 5th position: "))
    f1=float(input("Matrix B, 6th position: "))
    matrixB = np.array([[ a1, b1],[ d1, e1],[ g1, h1]])
    print(matrixB)
    print("Result of Matrix A multiply by Matrix B is: ")
    matrix = np.array([[a*a1+b*d1+c*g1,a*b1+b*e1+c*h1],[d*a1+e*d1+f*g1,d*b1+e*e1+f*h1],[g*a1+h*d1+i*g1,g*b1+h*e1+i*h1]])
    print(matrix)
elif dimension1 == "3x3" and dimension2 == "2x2":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "3x3" and dimension2 == "2x1":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "3x3" and dimension2 == "1x3":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "3x3" and dimension2 == "1x1":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "3x2" and dimension2 == "3x3":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "3x2" and dimension2 == "3x2":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "3x2" and dimension2 == "3x1":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "3x2" and dimension2 == "2x3":
    note = "Matrix A is 3x2 and Matrix B is 2x3"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    d=float(input("Matrix A, 4th position: "))
    e=float(input("Matrix A, 5th position: "))
    f=float(input("Matrix A, 6th position: "))
    matrixA = np.array([[ a, b],[ c, d],[ e, f]])
    print(matrixA)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    c1=float(input("Matrix B, 3rd position: "))
    d1=float(input("Matrix B, 4th position: "))
    e1=float(input("Matrix B, 5th position: "))
    f1=float(input("Matrix B, 6th position: "))
    matrixB = np.array([[ a1, b1, c1],[d1,e1,f1]])
    print(matrixB)
    print("Result of Matrix A multiply by Matrix B is: ")
    matrix = matrix = np.array([[a*a1+b*d1, a*b1+b*e1, a*c1+b*f1],[c*a1+d*d1, c*b1+d*e1, c*c1+d*f1],[e*a1+f*d1, e*b1+f*e1, e*c1+f*f1]])
    print(matrix)
elif dimension1 == "3x2" and dimension2 == "2x1":
    note = "Matrix A is 3x2 and Matrix B is 2x1"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    d=float(input("Matrix A, 4th position: "))
    e=float(input("Matrix A, 5th position: "))
    f=float(input("Matrix A, 6th position: "))
    matrixA = np.array([[ a, b],[ c, d],[ e, f]])
    print(matrixA)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    matrixB = np.array ([[a1],[b1]])
    print(matrixB)
    print("Result of Matrix A multiply by Matrix B is: ")
    matrix = matrix = np.array([[a*a1+b*b1],[c*a1+d*b1],[e*a1+f*b1]])
    print(matrix)
elif dimension1 == "3x2" and dimension2 == "1x3":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "3x2" and dimension2 == "1x2":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "3x2" and dimension2 == "1x1":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "3x1" and dimension2 == "3x3":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "3x1" and dimension2 == "3x2":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "3x1" and dimension2 == "3x1":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "3x1" and dimension2 == "2x3":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "3x1" and dimension2 == "2x2":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "3x1" and dimension2 == "2x1":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "3x1" and dimension2 == "1x3":
    note = "Matrix A is 3x1 and Matrix B is 1x3"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    matrixA = np.array([[a],[b],[c]])
    print(matrixA)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    c1=float(input("Matrix B, 3rd position: "))
    matrixB = np.array ([a1,b1,c1])
    print(matrixB)
    print("Result of Matrix A multiply by Matrix B is: ")
    matrix = matrix = np.array ([[a*a1,a*b1,a*c1],[b*a1,b*b1,b*c1],[c*a1,c*b1,c*c1]])
    print(matrix)
elif dimension1 == "3x1" and dimension2 == "1x2":
    note = "Matrix A is 3x1 and Matrix B is 1x2"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    matrixA = np.array([[a],[b],[c]])
    print(matrixA)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    matrixB = np.array ([a1,b1])
    print(matrixB)
    print("Result of Matrix A multiply by Matrix B is: ")
    matrix = matrix = np.array ([[a*a1,a*b1],[b*a1,b*b1],[c*a1,c*b1]])
    print(matrix)
elif dimension1 == "3x1" and dimension2 == "1x1":
    note = "Matrix A is 3x1 and Matrix B is 1x1"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    matrixA = np.array([[a],[b],[c]])
    print(matrixA)
    a1=float(input("Matrix B, 1st position: "))
    matrixB = np.array ([a1])
    print(matrixB)
    print("Result of Matrix A multiply by Matrix B is: ")
    matrix = matrix = np.array ([[a*a1],[b*a1],[c*a1]])
    print(matrix)
elif dimension1 == "2x3" and dimension2 == "3x3":
    note = "Matrix A is 2x3 and Matrix B is 3x3"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    d=float(input("Matrix A, 4th position: "))
    e=float(input("Matrix A, 5th position: "))
    f=float(input("Matrix A, 6th position: "))
    matrixA = np.array([[a,b,c],[d,e,f]])
    print(matrixA)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    c1=float(input("Matrix B, 3rd position: "))
    d1=float(input("Matrix B, 4th position: "))
    e1=float(input("Matrix B, 5th position: "))
    f1=float(input("Matrix B, 6th position: "))
    g1=float(input("Matrix B, 7th position: "))
    h1=float(input("Matrix B, 8th position: "))
    i1=float(input("Matrix B, 9th position: "))
    matrixB = np.array([[ a1, b1, c1],[ d1, e1, f1],[g1 ,h1 ,i1]])
    print(matrixB)
    print("Result of Matrix A multiply by Matrix B is: ")
    matrix = np.array ([[a*a1+b*d1+c*g1,a*b1+b*e1+c*h1,a*c1+b*f1+c*i1],[d*a1+e*d1+f*g1,d*b1+e*e1+f*h1,d*c1+e*f1+f*i1]])
    print(matrix)
elif dimension1 == "2x3" and dimension2 == "3x2":
    note = "Matrix A is 2x3 and Matrix B is 3x2"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    d=float(input("Matrix A, 4th position: "))
    e=float(input("Matrix A, 5th position: "))
    f=float(input("Matrix A, 6th position: "))
    matrixA = np.array([[a,b,c],[d,e,f]])
    print(matrixA)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    c1=float(input("Matrix B, 3rd position: "))
    d1=float(input("Matrix B, 4th position: "))
    e1=float(input("Matrix B, 5th position: "))
    f1=float(input("Matrix B, 6th position: "))
    matrixB = np.array([[a1, b1],[c1,d1],[e1,f1]])
    print(matrixB)
    print("Result of Matrix A multiply by Matrix B is: ")
    matrix = np.array ([[a*a1+b*c1+c*e1,a*b1+b*d1+c*f1],[d*a1+e*c1+f*e1,d*b1+e*d1+f*f1]])
    print(matrix)
elif dimension1 == "2x3" and dimension2 == "3x1":
    note = "Matrix A is 2x3 and Matrix B is 3x1"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    d=float(input("Matrix A, 4th position: "))
    e=float(input("Matrix A, 5th position: "))
    f=float(input("Matrix A, 6th position: "))
    matrixA = np.array([[a,b,c],[d,e,f]])
    print(matrixA)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    c1=float(input("Matrix B, 3rd position: "))
    matrixB = np.array([[a1],[b1],[c1]])
    print(matrixB)
    print("Result of Matrix A multiply by Matrix B is: ")
    matrix = np.array ([[a*a1+b*b1+c*c1],[d*a1+e*b1+f*c1]])
    print(matrix)
elif dimension1 == "2x3" and dimension2 == "2x3":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "2x3" and dimension2 == "2x2":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "2x3" and dimension2 == "2x1":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "2x3" and dimension2 == "1x3":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "2x3" and dimension2 == "1x2":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "2x3" and dimension2 == "1x1":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "2x2" and dimension2 == "3x3":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "2x2" and dimension2 == "3x2":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "2x2" and dimension2 == "3x1":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "2x2" and dimension2 == "1x3":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "2x2" and dimension2 == "1x2":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "2x2" and dimension2 == "1x1":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "2x2" and dimension2 == "2x3":
    note = "Matrix A is 2x2 and Matrix B is 2x3"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    d=float(input("Matrix A, 4th position: "))
    matrixA = np.array([[a,b],[c,d]])
    print(matrixA)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    c1=float(input("Matrix B, 3rd position: "))
    d1=float(input("Matrix B, 4th position: "))
    e1=float(input("Matrix B, 5th position: "))
    f1=float(input("Matrix B, 6th position: "))
    matrixB = np.array([[a1,b1,c1],[d1,e1,f1]])
    print(matrixB)
    print("Result of Matrix A multiply by Matrix B is: ")
    matrix = np.array ([[a*a1+b*d1,a*b1+b*e1,a*c1+b*f1],[c*a1+d*d1,c*b1+d*e1,c*c1+d*f1]])
    print(matrix)
elif dimension1 == "2x2" and dimension2 == "2x2":
    note = "Matrix A is 2x2 and Matrix B is 2x2"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    d=float(input("Matrix A, 4th position: "))
    matrixA = np.array([[a,b],[c,d]])
    print(matrixA)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    c1=float(input("Matrix B, 3rd position: "))
    d1=float(input("Matrix B, 4th position: "))
    matrixB = np.array([[a1,b1],[c1,d1]])
    print(matrixB)
    print("Result of Matrix A multiply by Matrix B is: ")
    matrix = np.array ([[a*a1+b*c1,a*b1+b*d1],[c*a1+d*c1,c*b1+d*d1]])
    print(matrix)
elif dimension1 == "2x2" and dimension2 == "2x1":
    note = "Matrix A is 2x2 and Matrix B is 2x1"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    d=float(input("Matrix A, 4th position: "))
    matrixA = np.array([[a,b],[c,d]])
    print(matrixA)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    matrixB = np.array([[a1],[b1]])
    print(matrixB)
    print("Result of Matrix A multiply by Matrix B is: ")
    matrix = np.array ([[a*a1+b*b1],[c*a1+d*b1]])
    print(matrix)
elif dimension1 == "2x1" and dimension2 == "3x3":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "2x1" and dimension2 == "3x2":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "2x1" and dimension2 == "3x1":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "2x1" and dimension2 == "2x3":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "2x1" and dimension2 == "2x2":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "2x1" and dimension2 == "2x1":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "2x1" and dimension2 == "1x3":
    note = "Matrix A is 2x1 and Matrix B is 1x3"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    matrixA = np.array([[a],[b]])
    print(matrixA)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    c1=float(input("Matrix B, 3rd position: "))
    matrixB = np.array([a1,b1,c1])
    print(matrixB)
    print("Result of Matrix A multiply by Matrix B is: ")
    matrix = np.array ([[a*a1,a*b1,a*c1],[b*a1,b*b1,b*c1]])
    print(matrix)
elif dimension1 == "2x1" and dimension2 == "1x2":
    note = "Matrix A is 2x1 and Matrix B is 1x2"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    matrixA = np.array([[a],[b]])
    print(matrixA)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    matrixB = np.array([a1,b1])
    print(matrixB)
    print("Result of Matrix A multiply by Matrix B is: ")
    matrix = np.array ([[a*a1,a*b1],[b*a1,b*b1]])
    print(matrix)
elif dimension1 == "2x1" and dimension2 == "1x1":
    note = "Matrix A is 2x1 and Matrix B is 1x1"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    matrixA = np.array([[a],[b]])
    print(matrixA)
    a1=float(input("Matrix B, 1st position: "))
    matrixB = np.array([a1])
    print(matrixB)
    print("Result of Matrix A multiply by Matrix B is: ")
    matrix = np.array ([[a*a1],[b*a1]])
    print(matrix)
elif dimension1 == "1x3" and dimension2 == "2x3":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "1x3" and dimension2 == "2x2":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "1x3" and dimension2 == "2x1":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "1x3" and dimension2 == "1x3":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "1x3" and dimension2 == "1x2":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "1x3" and dimension2 == "1x1":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "1x3" and dimension2 == "3x3":
    note = "Matrix A is 1x3 and Matrix B is 3x3"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    matrixA = np.array([a,b,c])
    print(matrixA)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    c1=float(input("Matrix B, 3rd position: "))
    d1=float(input("Matrix B, 4th position: "))
    e1=float(input("Matrix B, 5th position: "))
    f1=float(input("Matrix B, 6th position: "))
    g1=float(input("Matrix B, 7th position: "))
    h1=float(input("Matrix B, 8th position: "))
    i1=float(input("Matrix B, 9th position: "))
    matrixB = np.array([[ a1, b1, c1],[ d1, e1, f1],[g1 ,h1 ,i1]])
    print(matrixB)
    print("Result of Matrix A multiply by Matrix B is: ")
    matrix = np.array ([a*a1+b*d1+c*g1,a*b1+b*e1+c*h1,a*c1+b*f1+c*i1])
    print(matrix)
elif dimension1 == "1x3" and dimension2 == "3x2":
    note = "Matrix A is 1x3 and Matrix B is 3x2"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    matrixA = np.array([a,b,c])
    print(matrixA)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    c1=float(input("Matrix B, 3rd position: "))
    d1=float(input("Matrix B, 4th position: "))
    e1=float(input("Matrix B, 5th position: "))
    f1=float(input("Matrix B, 6th position: "))
    matrixB = np.array([[a1,b1],[c1,d1],[e1,f1]])
    print(matrixB)
    print("Result of Matrix A multiply by Matrix B is: ")
    matrix = np.array ([[a*a1+b*c1+c*e1,a*b1+b*d1+c*f1]])
    print(matrix)
elif dimension1 == "1x3" and dimension2 == "3x1":
    note = "Matrix A is 1x3 and Matrix B is 3x1"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    matrixA = np.array([a,b,c])
    print(matrixA)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    c1=float(input("Matrix B, 3rd position: "))
    matrixB = np.array([[a1],[b1],[c1]])
    print(matrixB)
    print("Result of Matrix A multiply by Matrix B is: ")
    matrix = np.array ([a*a1+b*b1+c*c1])
    print(matrix)
elif dimension1 == "1x2" and dimension2 == "3x3":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "1x2" and dimension2 == "3x2":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "1x2" and dimension2 == "3x1":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "1x2" and dimension2 == "1x3":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "1x2" and dimension2 == "1x2":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "1x2" and dimension2 == "1x1":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "1x2" and dimension2 == "2x3":
    note = "Matrix A is 1x2 and Matrix B is 2x3"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    matrixA = np.array([a,b])
    print(matrixA)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    c1=float(input("Matrix B, 3rd position: "))
    d1=float(input("Matrix B, 4th position: "))
    e1=float(input("Matrix B, 5th position: "))
    f1=float(input("Matrix B, 6th position: "))
    matrixB = np.array([[a1,b1,c1],[d1,e1,f1]])
    print(matrixB)
    print("Result of Matrix A multiply by Matrix B is: ")
    matrix = np.array ([a*a1+b*d1,a*b1+b*e1,a*c1+b*f1])
    print(matrix)
elif dimension1 == "1x2" and dimension2 == "2x2":
    note = "Matrix A is 1x2 and Matrix B is 2x2"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    matrixA = np.array([a,b])
    print(matrixA)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    c1=float(input("Matrix B, 3rd position: "))
    d1=float(input("Matrix B, 4th position: "))
    matrixB = np.array([[a1,b1],[c1,d1]])
    print(matrixB)
    print("Result of Matrix A multiply by Matrix B is: ")
    matrix = np.array ([a*a1+b*c1,a*b1+b*d1])
    print(matrix)
elif dimension1 == "1x2" and dimension2 == "2x1":
    note = "Matrix A is 1x2 and Matrix B is 2x1"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    matrixA = np.array([a,b])
    print(matrixA)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("matrix B, 2nd position: "))
    matrixB = np.array([[a1],[b1]])
    print(matrixB)
    print("Result of Matrix A multiply by Matrix B is: ")
    matrix = np.array ([a*a1+b*b1])
    print(matrix)
elif dimension1 == "1x1" and dimension2 == "3x3":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "1x1" and dimension2 == "3x2":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "1x1" and dimension2 == "3x1":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "1x1" and dimension2 == "2x3":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "1x1" and dimension2 == "2x2":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "1x1" and dimension2 == "2x1":
    print("Matrix A can not be multiplied by Matrix B")
elif dimension1 == "1x1" and dimension2 == "1x3":
    note = "Matrix A is 1x1 and Matrix B is 1x3"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    matrixA = np.array([a])
    print(matrixA)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    c1=float(input("Matrix B, 3rd position: "))
    matrixB = np.array([a1,b1,c1])
    print(matrixB)
    print("Result of Matrix A multiply by Matrix B is: ")
    matrix = np.array ([a*a1,a*b1,a*c1])
    print(matrix)
elif dimension1 == "1x1" and dimension2 == "1x2":
    note = "Matrix A is 1x1 and Matrix B is 1x2"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    matrixA = np.array([a])
    print(matrixA)
    a1=float(input("Matrix B, 1st position: "))
    b1=float(input("Matrix B, 2nd position: "))
    matrixB = np.array([a1,b1])
    print(matrixB)
    print("Result of Matrix A multiply by Matrix B is: ")
    matrix = np.array ([a*a1,a*b1])
    print(matrix)
elif dimension1 == "1x1" and dimension2 == "1x1":
    note = "Matrix A is 1x1 and Matrix B is 1x1"
    print(note)
    a=float(input("Matrix A, 1st position: "))
    matrixA = np.array([a])
    print(matrixA)
    a1=float(input("Matrix B, 1st position: "))
    matrixB = np.array([a1])
    print(matrixB)
    print("Result of Matrix A multiply by Matrix B is: ")
    matrix = np.array ([a*a1])
    print(matrix)


Please choose dimension for matrix A: 3x1
Please choose dimension for matrix B: 1x3
Matrix A is 3x1 and Matrix B is 1x3
Matrix A, 1st position: 4
Matrix A, 2nd position: 5
Matrix A, 3rd position: 6
[[4.]
 [5.]
 [6.]]
Matrix B, 1st position: 1
Matrix B, 2nd position: 2
Matrix B, 3rd position: 3
[1. 2. 3.]
Result of Matrix A multiply by Matrix B is: 
[[ 4.  8. 12.]
 [ 5. 10. 15.]
 [ 6. 12. 18.]]


In [48]:
#Find transpose of matrix:
import numpy as np
dimension = str(input("Please choose dimension: "))
if dimension == "3x3":
    print("You choosed dimension to transpose is 3x3")
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    d=float(input("Matrix A, 4th position: "))
    e=float(input("Matrix A, 5th position: "))
    f=float(input("Matrix A, 6th position: "))
    g=float(input("Matrix A, 7th position: "))
    h=float(input("Matrix A, 8th position: "))
    i=float(input("Matrix A, 9th position: "))
    matrix = np.array([[a,b,c],[d,e,f],[g,h,i]])
    print(matrix)
    print("Tranpose of the matrix is: ")
    matrixT = np.array([[a,d,g],[b,e,h],[c,f,i]])
    print(matrixT)
elif dimension == "3x2":
    print("You choosed dimension to transpose is 3x2")
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    d=float(input("Matrix A, 4th position: "))
    e=float(input("Matrix A, 5th position: "))
    f=float(input("Matrix A, 6th position: "))
    matrix = np.array([[a,b],[c,d],[e,f]])
    print(matrix)
    print("Tranpose of the matrix is: ")
    matrixT = np.array([[a,c,e],[b,d,f]])
    print(matrixT)
elif dimension == "3x1":
    print("You choosed dimension to transpose is 3x1")
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    matrix = np.array([[a],[b],[c]])
    print(matrix)
    print("Tranpose of the matrix is: ")
    matrixT = np.array([a,b,c])
    print(matrixT)
elif dimension == "2x3":
    print("You choosed dimension to transpose is 2x3")
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    d=float(input("Matrix A, 4th position: "))
    e=float(input("Matrix A, 5th position: "))
    f=float(input("Matrix A, 6th position: "))
    matrix = np.array([[a,b,c],[d,e,f]])
    print(matrix)
    print("Tranpose of the matrix is: ")
    matrixT = np.array([[a,d],[b,e],[c,f]])
    print(matrixT)
elif dimension == "2x2":
    print("You choosed dimension to transpose is 2x2")
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    d=float(input("Matrix A, 4th position: "))
    matrix = np.array([[a,b],[c,d]])
    print(matrix)
    print("Tranpose of the matrix is: ")
    matrixT = np.array([[a,c,],[b,d]])
    print(matrixT)
elif dimension == "2x1":
    print("You choosed dimension to transpose is 2x2")
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    matrix = np.array([[a],[b]])
    print(matrix)
    print("Tranpose of the matrix is: ")
    matrixT = np.array([a,b])
    print(matrixT)
elif dimension == "1x3":
    print("You choosed dimension to transpose is 1x3")
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    matrix = np.array([a,b,c])
    print(matrix)
    print("Tranpose of the matrix is: ")
    matrixT = np.array([a,b])
    print(matrixT)
elif dimension == "1x2":
    print("You choosed dimension to transpose is 1x2")
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    matrix = np.array([a,b])
    print(matrix)
    print("Tranpose of the matrix is: ")
    matrixT = np.array([[a],[b]])
    print(matrixT)
elif dimension == "1x1":
    print("You choosed dimension to transpose is 1x1")
    a=float(input("Matrix A, 1st position: "))
    print("Matrix and Tranpose of the matrix is the same")
    matrixT = np.array([a])
    print(matrixT)
    

Please choose dimension: 1x1
You choosed dimension to transpose is 1x1
Matrix A, 1st position: 5
 Matrix and Tranpose of the matrix is the same
[5.]


In [7]:
# Find inverse matrix:
import numpy as np
dimension = str(input("Please choose dimension: "))
if dimension == "2x2":
    print("Your dimension is 2x2")
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    d=float(input("Matrix A, 4th position: "))
    matrix = np.array([[a,b],[c,d]])
    print("Your orginal matrix is: ")
    print(matrix)
    diterminant = a*d-c*b
    scalar = 1/diterminant
    if diterminant == 0:
        print("Your matrix has no inverse")
    elif diterminant != 0:
        matrixinverse = np.array([[scalar*d,scalar*(-b)],[scalar*(-c),scalar*a]])
        print("Your inverse matrix is: ")
        print(matrixinverse)
elif dimension == "3x3":
    print("Your dimension is 3x3")
    a=float(input("Matrix A, 1st position: "))
    b=float(input("Matrix A, 2nd position: "))
    c=float(input("Matrix A, 3rd position: "))
    d=float(input("Matrix A, 4th position: "))
    e=float(input("Matrix A, 5th position: "))
    f=float(input("Matrix A, 6th position: "))
    g=float(input("Matrix A, 7th position: "))
    h=float(input("Matrix A, 8th position: "))
    i=float(input("Matrix A, 9th position: "))
    matrix = np.array([[a,b,c],[d,e,f],[g,h,i]])
    print("Your original matrix is: ")
    print(matrix)
    diterminant = a*(e*i-h*f) - b*(d*i-g*f) + c*(d*h-g*e)
    if diterminant == 0:
        print("Your matrix has no inverse")
    elif diterminant != 0:
        a1 = (e*i-f*h)/diterminant
        b1 = (b*i-c*h)/diterminant
        c1 = (b*f-c*e)/diterminant
        d1 = (d*i-f*g)/diterminant
        e1 = (a*i-c*g)/diterminant
        f1 = (a*f-c*d)/diterminant
        g1 = (d*h-e*g)/diterminant
        h1 = (a*h-b*g)/diterminant
        i1 = (a*e-b*d)/diterminant
        matrixinverse = np.array([[a1,-b1,c1],[-d1,e1,-f1],[g1,-h1,i1]])
        print("Your inverse matrix is: ")
        print(matrixinverse)
elif dimension == "4x4":
    print("your dimension is: 4x4")
    a11 = float(input("a11:"))
    a12 = float(input("a12:"))
    a13 = float(input("a13:"))
    a14 = float(input("a14:"))
    a21 = float(input("a21:"))
    a22 = float(input("a22:"))
    a23 = float(input("a23:"))
    a24 = float(input("a24:"))
    a31 = float(input("a31:"))
    a32 = float(input("a32:"))
    a33 = float(input("a33:"))
    a34 = float(input("a34:"))
    a41 = float(input("a41:"))
    a42 = float(input("a42:"))
    a43 = float(input("a43:"))
    a44 = float(input("a44:"))
    A = np.array([[a11,a12,a13,a14],[a21,a22,a23,a24],[a31,a32,a33,a34],[a41,a42,a43,a44]])
    print("Matrix A is:")
    print(A)
    determinant = a11*a22*a33*a44 + a11*a23*a34*a42 + a11*a24*a32*a43 + a12*a21*a34*a43 + a12*a23*a31*a44 + a12*a24*a33*a41 + a13*a21*a32*a44 + a13*a22*a34*a41 + a13*a24*a31*a42 + a14*a21*a33*a42 + a14*a22*a31*a43 + a14*a23*a32*a41 - a11*a22*a34*a43 - a11*a23*a32*a44 - a11*a24*a33*a42 - a12*a21*a33*a44 - a12*a23*a34*a41 - a12*a24*a31*a43 - a13*a21*a34*a42 - a13*a22*a31*a44 - a13*a24*a32*a41 - a14*a21*a32*a43 - a14*a22*a33*a41 - a14*a23*a31*a42
    if determinant == 0:
        print("This matrix does not have inverse")
    elif determinant != 0:
        b11 = (a22*a33*a44 + a23*a34*a42 + a24*a32*a43 - a22*a34*a43 - a23*a32*a44 - a24*a33*a42)/determinant
        b12 = (a12*a34*a43 + a13*a32*a44 + a14*a33*a42 - a12*a33*a44 - a13*a34*a42 - a14*a32*a43)/determinant
        b13 = (a12*a23*a44 + a13*a24*a42 + a14*a22*a43 - a12*a24*a43 - a13*a22*a44 - a14*a23*a42)/determinant
        b14 = (a12*a24*a33 + a13*a22*a34 + a14*a23*a32 - a12*a23*a34 - a13*a24*a32 - a14*a22*a33)/determinant
        b21 = (a21*a34*a43 + a23*a31*a44 + a24*a33*a41 - a21*a33*a44 - a23*a34*a41 - a24*a31*a43)/determinant
        b22 = (a11*a33*a44 + a13*a34*a41 + a14*a31*a43 - a11*a34*a43 - a13*a31*a44 - a14*a33*a41)/determinant
        b23 = (a11*a24*a43 + a13*a21*a44 + a14*a23*a41 - a11*a23*a44 - a13*a24*a41 - a14*a21*a43)/determinant
        b24 = (a11*a23*a34 + a13*a24*a31 + a14*a21*a33 - a11*a24*a33 - a13*a21*a34 - a14*a23*a31)/determinant
        b31 = (a21*a32*a44 + a22*a34*a41 + a24*a31*a42 - a21*a34*a42 - a22*a31*a44 - a24*a32*a41)/determinant
        b32 = (a11*a34*a42 + a12*a31*a44 + a14*a32*a41 - a11*a32*a44 - a12*a34*a41 - a14*a31*a42)/determinant
        b33 = (a11*a22*a44 + a12*a24*a41 + a14*a21*a42 - a11*a24*a42 - a12*a21*a44 - a14*a22*a41)/determinant
        b34 = (a11*a24*a32 + a12*a21*a34 + a14*a22*a31 - a11*a22*a34 - a12*a24*a31 - a14*a21*a32)/determinant
        b41 = (a21*a33*a42 + a22*a31*a43 + a23*a32*a41 - a21*a32*a43 - a22*a33*a41 - a23*a31*a42)/determinant
        b42 = (a11*a32*a43 + a12*a33*a41 + a13*a31*a42 - a11*a33*a42 - a12*a31*a43 - a13*a32*a41)/determinant
        b43 = (a11*a23*a42 + a12*a21*a43 + a13*a22*a41 - a11*a22*a43 - a12*a23*a41 - a13*a21*a42)/determinant
        b44 = (a11*a22*a33 + a12*a23*a31 + a13*a21*a32 - a11*a23*a32 - a12*a21*a33 - a13*a22*a31)/determinant
        matrixinverse = np.array([[b11,b12,b13,b14],[b21,b22,b23,b24],[b31,b32,b33,b34],[b41,b42,b43,b44]])
        print("Matrix Inverse of A is: ")
        print(matrixinverse)
        

Please choose dimension: 4x4
your dimension is: 4x4
a11:1
a12:5
a13:6
a14:4
a21:8
a22:9
a23:7
a24:5
a31:4
a32:8
a33:9
a34:4
a41:10
a42:5
a43:4
a44:6
Matrix A is:
[[ 1.  5.  6.  4.]
 [ 8.  9.  7.  5.]
 [ 4.  8.  9.  4.]
 [10.  5.  4.  6.]]
Matrix Inverse of A is: 
[[-0.26213592 -0.09708738  0.19417476  0.12621359]
 [ 0.14886731  0.52427184 -0.38187702 -0.2815534 ]
 [-0.22006472 -0.42718447  0.5210356   0.15533981]
 [ 0.45954693  0.00970874 -0.35275081  0.08737864]]


##### 2.	Create a program that solves to solve linear equations of any size

In [17]:
import numpy as np
print("Type of linear equation:")
type1 = "ax + by = c"
type2 = "ax + by + cz = d"
type3 = "ax^2 + bx + c = 0"
print("  1:",type1)
print("  2:",type2)
print("  3:",type3)
chosenType = str(input("Please choose linear equation type: "))
if chosenType == "1":
    print("Linear equation: ax + by = c")
    a=float(input("  Please input a: "))
    b=float(input("  Please input b: "))
    c=float(input("  Please input c: "))
    print("Your first linear equation is: ",a,"x"," + ",b," y ","=",c)
    #print("Linear equation: a1x + b1y = c1")
    a1=float(input("  Please input a1: "))
    b1=float(input("  Please input b1: "))
    c1=float(input("  Please input c1: "))
    print("Your second linear equation is: ",a1,"x"," + ",b1," y ","=",c1)
    diterminant = a*b1-a1*b
    scalar = 1/diterminant
    if diterminant == 0:
        print("Your matrix has no inverse")
    elif diterminant != 0:
        print("Your result: ")
        print("  x = ",(scalar*b1)*c + scalar*(-b)*c1)
        print("  y = ",(scalar*(-a1))*c + (scalar*a)*c1)
elif chosenType == "2":
    print("Linear equation: ax + by + cz = d")
    a=float(input("  Please input a: "))
    b=float(input("  Please input b: "))
    c=float(input("  Please input c: "))
    d=float(input("  Please input d: "))
    print("Your first linear equation is: ",a,"x"," + ",b,"y"," + ",c,"z","=",d)
    a1=float(input("  Please input a1: "))
    b1=float(input("  Please input b1: "))
    c1=float(input("  Please input c1: "))
    d1=float(input("  Please input d1: "))
    print("Your second linear equation is: ",a1,"x"," + ",b1,"y"," + ",c1,"z","=",d1)
    a2=float(input("  Please input a2: "))
    b2=float(input("  Please input b2: "))
    c2=float(input("  Please input c2: "))
    d2=float(input("  Please input d2: "))
    print("Your third linear equation is: ",a2,"x"," + ",b2,"y"," + ",c2,"z","=",d2)
    diterminant = a*(b1*c2-b2*c1) - b*(a1*c2-a2*c1) + c*(a1*b2-a2*b1)
    matrixTranspose = np.array([[a,a1,a2],[b,b1,b2],[c,c1,c2]])
    a3 = (b1*c2-c1*b2)/diterminant
    b3 = (b*c2-c*b2)/diterminant
    c3 = (b*c1-c*b1)/diterminant
    d3 = (a1*c2-c1*a2)/diterminant
    e3 = (a*c2-c*a2)/diterminant
    f3 = (a*c1-c*a1)/diterminant
    g3 = (a1*b2-b1*a2)/diterminant
    h3 = (a*b2-b*a2)/diterminant
    i3 = (a*b1-b*a1)/diterminant
    matrixInverse = np.array([[(a3*d-b3*d1+c3*d2)],[(-d3*d+e3*d1-f3*d2)],[(g3*d-h3*d1+i3*d2)]])
    print("The result is: ")
    print("x = ",(a3*d-b3*d1+c3*d2))
    print("y = ",(-d3*d+e3*d1-f3*d2))
    print("z = ",(g3*d-h3*d1+i3*d2))
elif chosenType == "3":
    print("Linear equation is: ax^2 + bx + c = 0 ")
    a=float(input("Input a: "))
    b=float(input("Input b: "))
    c=float(input("Input c: "))
    i = b**2-4*a*c
    if a == 0:
        x = -c/b
    elif a!= 0:
        x1 = (-b/(2*a))+((i**0.5)/(2*a))
        x2 = (-b/(2*a))-((i**0.5)/(2*a))
        print("x1 is:",x1)
        print("x2 is:",x2)
    

Type of linear equation:
  1: ax + by = c
  2: ax + by + cz = d
  3: ax^2 + bx + c = 0
Please choose linear equation type: 3
Linear equation is: ax^2 + bx + c = 0 
Input a: 100
Input b: 250
Input c: 100
x1 is: -0.5
x2 is: -2.0
